const ADJECTIVES = [
  'phantom', 'ghost', 'cipher', 'shadow', 'neon', 'cyber', 'stealth',
  'rogue', 'glitch', 'pixel', 'binary', 'crypt', 'nova', 'void',
  'dark', 'silent', 'toxic', 'hyper', 'turbo', 'zero', 'cosmic',
  'quantum', 'astral', 'storm', 'blaze', 'frost', 'venom', 'chaos'
];

const TRIVIA_QUESTIONS = [
  { q: 'What does SQL stand for?', options: ['Structured Query Language', 'Simple Question Language', 'Structured Question Logic', 'System Query Language'], answer: 0, category: 'tech' },
  { q: 'What port does HTTPS use by default?', options: ['80', '443', '8080', '22'], answer: 1, category: 'cyber' },
  { q: 'Which tool is used for network packet analysis?', options: ['Nmap', 'Wireshark', 'Metasploit', 'Burp Suite'], answer: 1, category: 'cyber' },
  { q: 'What does VPN stand for?', options: ['Virtual Private Network', 'Virtual Public Network', 'Visual Private Network', 'Verified Private Network'], answer: 0, category: 'tech' },
  { q: 'Which protocol is used for sending emails?', options: ['FTP', 'HTTP', 'SMTP', 'SSH'], answer: 2, category: 'tech' },
  { q: "What is a 'zero-day' vulnerability?", options: ['A bug found on day zero of development', 'An unknown exploit with no patch', 'A virus that activates at midnight', 'A deleted security log'], answer: 1, category: 'cyber' },
  { q: "What does the 'ping' command measure?", options: ['Bandwidth', 'Latency', 'DNS resolution', 'Packet loss only'], answer: 1, category: 'tech' },
  { q: 'Which language is most associated with web browsers?', options: ['Python', 'Java', 'JavaScript', 'C++'], answer: 2, category: 'tech' },
  { q: 'What is phishing?', options: ['A type of DDoS attack', 'Social engineering via fake emails/sites', 'A network scanning method', 'A firewall bypass technique'], answer: 1, category: 'cyber' },
  { q: 'What does RAM stand for?', options: ['Read Access Memory', 'Random Access Memory', 'Rapid Action Module', 'Runtime Application Memory'], answer: 1, category: 'tech' },
  { q: 'Which Linux command lists directory contents?', options: ['dir', 'ls', 'show', 'list'], answer: 1, category: 'tech' },
  { q: 'What is the default SSH port?', options: ['21', '22', '23', '25'], answer: 1, category: 'cyber' },
  { q: 'What does DDoS stand for?', options: ['Direct Denial of Service', 'Distributed Denial of Service', 'Digital Denial of System', 'Dynamic Denial of Server'], answer: 1, category: 'cyber' },
  { q: 'What is the purpose of a firewall?', options: ['Speed up internet', 'Encrypt all data', 'Filter network traffic', 'Store passwords'], answer: 2, category: 'cyber' },
  { q: 'What does API stand for?', options: ['Application Programming Interface', 'Automated Program Integration', 'Advanced Protocol Interface', 'Application Process Integration'], answer: 0, category: 'tech' },
  { q: 'Which planet is known as the Red Planet?', options: ['Venus', 'Mars', 'Jupiter', 'Saturn'], answer: 1, category: 'general' },
  { q: 'What is the chemical symbol for gold?', options: ['Go', 'Gd', 'Au', 'Ag'], answer: 2, category: 'general' },
  { q: 'How many continents are there?', options: ['5', '6', '7', '8'], answer: 2, category: 'general' },
  { q: 'What year did the first iPhone release?', options: ['2005', '2006', '2007', '2008'], answer: 2, category: 'general' },
  { q: 'Who painted the Mona Lisa?', options: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Van Gogh'], answer: 1, category: 'general' },
  { q: 'What is the largest ocean on Earth?', options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'], answer: 3, category: 'general' },
  { q: 'How many bones are in the adult human body?', options: ['186', '206', '216', '256'], answer: 1, category: 'general' },
  { q: 'What is the capital of Japan?', options: ['Osaka', 'Kyoto', 'Tokyo', 'Nagoya'], answer: 2, category: 'general' },
  { q: 'Which gas do plants absorb from the atmosphere?', options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen'], answer: 2, category: 'general' },
  { q: 'What is the speed of light (approx)?', options: ['300,000 km/s', '150,000 km/s', '500,000 km/s', '1,000,000 km/s'], answer: 0, category: 'general' },
  { q: "Who directed 'Inception'?", options: ['Steven Spielberg', 'Christopher Nolan', 'James Cameron', 'Ridley Scott'], answer: 1, category: 'movies' },
  { q: "What is the name of the AI in '2001: A Space Odyssey'?", options: ['ARIA', 'JARVIS', 'HAL 9000', 'WOPR'], answer: 2, category: 'movies' },
  { q: "Which movie features the quote 'I'll be back'?", options: ['RoboCop', 'Die Hard', 'The Terminator', 'Predator'], answer: 2, category: 'movies' },
  { q: "In 'The Matrix', what color pill does Neo take?", options: ['Blue', 'Red', 'Green', 'Yellow'], answer: 1, category: 'movies' },
  { q: 'Which fictional company does Iron Man run?', options: ['Wayne Enterprises', 'Stark Industries', 'Oscorp', 'LexCorp'], answer: 1, category: 'movies' },
  { q: 'What is the most popular programming language (2024)?', options: ['Python', 'JavaScript', 'Java', 'C++'], answer: 0, category: 'tech' },
  { q: "What does 'HTTP' stand for?", options: ['HyperText Transfer Protocol', 'High Tech Transfer Process', 'Hyper Terminal Transfer Protocol', 'Host Transfer Text Protocol'], answer: 0, category: 'tech' },
  { q: 'Which company created the Android OS?', options: ['Apple', 'Microsoft', 'Google', 'Samsung'], answer: 2, category: 'tech' },
  { q: "What is 'localhost' IP address?", options: ['192.168.1.1', '10.0.0.1', '127.0.0.1', '0.0.0.0'], answer: 2, category: 'tech' },
  { q: 'What animal is the Linux mascot?', options: ['Fox', 'Penguin', 'Cat', 'Dog'], answer: 1, category: 'tech' },
  { q: 'How many bits in a byte?', options: ['4', '8', '16', '32'], answer: 1, category: 'tech' },
  { q: 'What is the hardest natural substance?', options: ['Titanium', 'Quartz', 'Diamond', 'Sapphire'], answer: 2, category: 'general' },
  { q: 'What year was the World Wide Web invented?', options: ['1985', '1989', '1991', '1995'], answer: 1, category: 'tech' },
  { q: 'Which country has the most internet users?', options: ['USA', 'India', 'China', 'Brazil'], answer: 2, category: 'general' },
  { q: "What does 'GPU' stand for?", options: ['General Processing Unit', 'Graphics Processing Unit', 'Global Processing Unit', 'Graphical Power Unit'], answer: 1, category: 'tech' },
  { q: 'What is the smallest country in the world?', options: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'], answer: 1, category: 'general' },
  { q: "Which key combination is 'Undo' on Windows?", options: ['Ctrl+Z', 'Ctrl+X', 'Ctrl+U', 'Ctrl+Y'], answer: 0, category: 'tech' },
  { q: 'What does CSS stand for?', options: ['Computer Style Sheets', 'Cascading Style Sheets', 'Creative Style System', 'Coded Style Syntax'], answer: 1, category: 'tech' },
  { q: 'Which planet has the most moons?', options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'], answer: 1, category: 'general' },
  { q: 'What is the binary representation of the number 10?', options: ['1010', '1100', '1001', '1110'], answer: 0, category: 'tech' },
  { q: 'Who founded SpaceX?', options: ['Jeff Bezos', 'Elon Musk', 'Richard Branson', 'Bill Gates'], answer: 1, category: 'general' },
  { q: 'What is the most spoken language in the world?', options: ['English', 'Spanish', 'Hindi', 'Mandarin Chinese'], answer: 3, category: 'general' },
  { q: 'In which year did Bitcoin launch?', options: ['2007', '2008', '2009', '2010'], answer: 2, category: 'tech' },
  { q: "What does 'IoT' stand for?", options: ['Internet of Things', 'Integration of Tech', 'Internal of Terminals', 'Internet of Terminals'], answer: 0, category: 'tech' },
];

const TYPE_PROMPTS = [
  'The quick brown fox jumps over the lazy dog',
  'sudo apt update && sudo apt upgrade -y',
  "console.log('Hello, World!');",
  'SELECT * FROM users WHERE active = true;',
  "git commit -m 'fix: resolve critical security bug'",
  'nmap -sV -sC -oN scan.txt 192.168.1.0/24',
  'All your base are belong to us',
  "import hashlib; print(hashlib.sha256(b'password').hexdigest())",
  'The five boxing wizards jump quickly at dawn',
  'docker run -d -p 3000:3000 --name app my-image',
  "while true; do echo 'hacking...'; sleep 1; done",
  "curl -X POST https://api.example.com/data -H 'Content-Type: application/json'",
  'function encrypt(data, key) { return cipher(data, key); }',
  'Pack my box with five dozen liquor jugs',
  'ssh -i ~/.ssh/id_rsa admin@192.168.1.100',
  'The matrix has you. Follow the white rabbit.',
  'chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys',
  'Every great developer was once a beginner who refused to give up',
  'python3 -m http.server 8080 --bind 0.0.0.0',
  'rm -rf node_modules && npm install --legacy-peer-deps',
];

const CHARADES_WORDS = [
  'pizza', 'rocket', 'ghost', 'rainbow', 'sunset', 'dancing', 'basketball',
  'sleeping', 'swimming', 'airplane', 'birthday', 'wedding', 'earthquake',
  'volcano', 'snowman', 'surfing', 'camping', 'fishing', 'painting',
  'singing', 'cooking', 'running', 'reading', 'driving', 'shopping',
  'football', 'guitar', 'diamond', 'treasure', 'pirate', 'zombie',
  'dragon', 'unicorn', 'wizard', 'robot', 'alien', 'ninja', 'samurai',
  'cowboy', 'detective', 'firefighter', 'astronaut', 'superhero',
  'thunderstorm', 'beach', 'mountain', 'jungle', 'desert', 'ocean'
];

const WYR_PROMPTS = [
  { a: 'Have super speed', b: 'Have super strength' },
  { a: 'Be able to fly', b: 'Be able to turn invisible' },
  { a: 'Live without music', b: 'Live without movies' },
  { a: 'Always speak the truth', b: 'Always detect lies' },
  { a: 'Have unlimited WiFi everywhere', b: 'Have unlimited battery life' },
  { a: 'Be a master hacker', b: 'Be a master social engineer' },
  { a: 'Know every programming language', b: 'Know every spoken language' },
  { a: 'Live in the future (2200)', b: 'Live in the past (1800)' },
  { a: 'Have a photographic memory', b: 'Have the ability to forget anything at will' },
  { a: 'Be famous but poor', b: 'Be unknown but rich' },
  { a: 'Debug code for 8 hours', b: 'Write documentation for 8 hours' },
  { a: 'Only use dark mode forever', b: 'Only use light mode forever' },
  { a: 'Have no bugs in your code', b: 'Have 10x faster coding speed' },
  { a: 'Work from anywhere', b: 'Work at your dream company' },
  { a: 'Know when you will die', b: 'Know how you will die' },
  { a: 'Travel to space', b: 'Travel to the bottom of the ocean' },
  { a: 'Have free food for life', b: 'Have free travel for life' },
  { a: 'Be the smartest person alive', b: 'Be the happiest person alive' },
  { a: 'Live without internet', b: 'Live without air conditioning' },
  { a: 'Fight 100 duck-sized horses', b: 'Fight 1 horse-sized duck' },
  { a: 'Have a rewind button for life', b: 'Have a pause button for life' },
  { a: 'Speak every language', b: 'Play every instrument' },
  { a: 'Read minds', b: 'Control minds' },
  { a: 'Never use a mouse again', b: 'Never use a keyboard again' },
  { a: 'Be a pentester', b: 'Be a threat analyst' },
  { a: 'Live in a simulation', b: 'Live in the real world knowing it is boring' },
  { a: 'Have unlimited storage', b: 'Have unlimited RAM' },
  { a: 'Master cybersecurity', b: 'Master AI/ML' },
  { a: 'Always have the latest phone', b: 'Always have the fastest laptop' },
  { a: 'Be stuck in a time loop', b: 'Be stuck in a parallel universe' },
];

module.exports = {
  ADJECTIVES,
  TRIVIA_QUESTIONS,
  TYPE_PROMPTS,
  CHARADES_WORDS,
  WYR_PROMPTS,
};
